[workspace]
members = ["nj_lib", "cli", "wasm", "python"]
resolver = "3"

[workspace.package]
version = "0.0.2"
edition = "2024"
authors = ["Rens Holmer"]
license = "MIT"
repository = "https://github.com/holmrenser/nj.rs"
