[package]
name = "nj_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true


[[bin]]
name = "nj"
path = "src/main.rs"


[dependencies]
clap = { version = "4", features = ["derive"] }
nj_lib = { path = "../nj_lib" }
