[package]
name = "nj_cli"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "nj"
path = "src/main.rs"


[dependencies]
clap = { version = "4", features = ["derive"] }
nj_lib = { path = "../nj_lib" }
