[package]
name = "nj_py"
version = "0.0.1"
edition = "2021"

[lib]
name = "nj_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module"] }
nj_lib = { path = "../nj_lib" }
serde_json = "1.0.145"
serde-pyobject = "0.8.0"
